# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file into the container
COPY data-inserter-requirements.txt .

# Install any dependencies
RUN pip install --no-cache-dir -r data-inserter-requirements.txt

# Copy the current directory contents into the container
COPY data_inserter.py .

# Command to run the data insertion script and then keep the container alive
CMD ["sh", "-c", "python data_inserter.py && tail -f /dev/null"]
